language: java
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install org.jacoco:jacoco-maven-plugin:report org.sonarsource.scanner.maven:sonar-maven-plugin:3.9.0.2155:sonar -Dsonar.projectKey=codesseur_data-structure

after_success:
  - mvn coveralls:report

addons:
  sonarcloud:
    organization: "codesseur"
    token:
      secure: "l7WTB3x7juzTYlkfqs4wGu3JNpeC2umuzVprqV8s9PlB0Wf02BY/fwwC07FDTh9d9g/iUWR7ombeELpuidedEuCeCgxXP+z9c9ebgwtzUJmRmieuWUSd45HT+RBlwjDlEJ00UAKSXdSfFHC/ErZMHVqpYAMATGQptv5XWs4cb95POKpBzFMxSrO6rTWHnRsbMi7GF4pMt5H7nKjO4CxphQhLyIH5JMNjDvKoobxV7EKQefTbKq7PRWGD1ig+nsJqEKevqdKIFFp11QvcH5Fonf677Np0oBLk6wB70CmD/pim2ffD49KSMRmhDer5xUbtz/No0gBDYwLkzpIeGIhOxoDFFSCkz8IxEewHdQuN72cVuXZ1Vlf13PlDHU0uXxvVOnm7FlTmW9qB4JJ6N/1xJXZ+xg7yMK+70GAGFAhtO0uxv6w/aIUsaKt3BnuT8x3U398CCt0HGZMsezRDgzoe366IcOMOvkMss5BHuCFpUeuVMmSBz8v+UPNKWQEn1nhMXupXPabmcXbVm7mgTZQ/m+i8cD4a0g8y0l1s+8iK32V8xlC4MxeVe5brGw4crB/zePpoCc4mLnrJZ/Yu2wh2ka8RcRjHyILCFCYtvNzEiusdWoN7YO/EJVW3X4B/8qN2NCkvjcii5m3DDiWzZKlMM27sv30eTKZRB866TPRllqQ="

cache:
  directories:
    - '$HOME/.m2/repository'

jdk:
  - oraclejdk11