language: java
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install org.jacoco:jacoco-maven-plugin:report org.sonarsource.scanner.maven:sonar-maven-plugin:3.9.0.2155:sonar -Dsonar.projectKey=codesseur_data-structure

after_success:
  - mvn coveralls:report

addons:
  sonarcloud:
    organization: "codesseur"
    token:
      secure: "TLmeS5Y/GVQjTzyOu32kdhiwFjb1aByMtIatVxIgbny/nWrLLlgudQhOEdSmO4FQVNT7qLn4ft+fwHZ+e8vIqBtlmdUGRcNyjjs2pUurbd3Am5ItATJ8igsUPN/x4NxbU4OaKk+sA1T5cEaO5J3h4eFZAybTNpkAX4FDdEWOY/Js/fHI3ZM/5mcMSS7wTOkwz15ZDYJzoL8xjTO6Wk+YOJRB9jpnXRAThWBmgHPgWyzz3D1oK3lk918EhInCOALBQ5kW4xLUzZ9h4kBHiG0N58LdDWoXGgCSta0gjdM9zd+BWsLF5k16g5T5aCTimpzLTcw0fNTqrixlb9Gp/LKAilOsUioz/l6RbjtCtUlJE7JGAW4bSnDHYQLxtVeuj5afG8CxOa3OkPLgS2szOZEay9ZK+QHA9Wdm+hMzo+JV+SCLl9tH+xqYMvxRYIpGQfle1jMXJ5Z/uHr4Ezpi21bsgvHghGmqaXudULi71TBr7MUIEkzMt2BzgJpMDkMu4ZJKioMWRGPzpYYaU1Iwhs1Vs29XqnFUyug/54LXsBq1ZMxU2ZoyvxqmqMVY8pG+M9WdOctToCMOtl1PZw97/UxcJqKkeGzpJQSvcjQFEIBVHVhe6PabCsvzRG+DV340vNmFRUEXUZVK2AodPagX0lhJbAUdc9GlTOVS1v5rsUW7E00="

cache:
  directories:
    - '$HOME/.m2/repository'

jdk:
  - oraclejdk11