language: java
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install org.jacoco:jacoco-maven-plugin:report org.sonarsource.scanner.maven:sonar-maven-plugin:3.9.0.2155:sonar -Dsonar.projectKey=codesseur_data-structure

after_success:
  - mvn coveralls:report

addons:
  sonarcloud:
    organization: "codesseur"
    token:
      secure: "Ihy8/9fholV1kvlA8jfdhkmImiUnEXVwmuLmj5Wrq+DRamDgeNeEcxfBufCNNPOPZ70J442cBbpaD/M7wILVc8WFI+oq4/ZoBJ8nKBoV2cCdObq4P1B4TBQtK4NOd1c7xrZBSR+2rB17EUAQmuK9E/pD+KjfSJUCnbJABlu/ny5cjRpSa3kswph/a2yuzZ6vm7HDftHOAnNL8R7TLiG/F0FB0qN9arVD/Q8AgbZMm6HOZhC1A8I4I1T7DF4pqH+bixcG4O52kIqCqkao5Zntj4Zz2Am8BJ7cdizaKNb1WWFOP96hM43c8HyqSrG9ht7mpu2HwU+uQKaM0ZBUtlo/CYqYLDhxATJU3IDdTNhPRnZqkdSq4Q+f9nzBXxvyPO7XLSwB2azPT70EOLBkhvsC4yzMCSG2RjKx8hxSkDGnSmfeJDhoSdel8zwipF9jO6enFina9tfYyOXVRmDxGhKex/0Mc9e9WiCliiRZzJEF1a6FrkSudckzrawo6V8LoNQhptKybmggCeBeC36yikFKE5grGEBjiJk/HEI0t0n7ubiPk7uX8Rf5A/CLX6mKUwvrpSZ4pSVn3Q1gnycCvKi6+PasntUNmUXNHGcshVhDeUA2baGJPtJ2hRVzdYdnkXyDAj+m9gZsYii/DlJ97ApjCdpYhkP59UWmoCsdh3sYde8="

cache:
  directories:
    - '$HOME/.m2/repository'

jdk:
  - oraclejdk11