language: java

addons:
  sonarcloud:
    organization: "codesseur"

script:
  #- mvn -X clean org.jacoco:jacoco-maven-plugin:prepare-agent install org.jacoco:jacoco-maven-plugin:report org.sonarsource.scanner.maven:sonar-maven-plugin:3.9.0.2155:sonar -Dsonar.projectKey=codesseur_data-structure
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install org.jacoco:jacoco-maven-plugin:report sonar:sonar -Dsonar.projectKey=codesseur_data-structure

after_success:
  - mvn coveralls:report

cache:
  directories:
    - '$HOME/.m2/repository'

jdk:
  - oraclejdk11