language: java
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=codesseur_better-stream

after_success:
  - mvn clean test jacoco:report coveralls:report

addons:
  sonarcloud:
    organization: "codesseur"
    token:
      secure: "v5TanPnRd3ngxM0ibGnnare3N8yzg2T+4OdUIAp2H3HExSYUtHIwK3tNIo01ezwnHNgU+5Iru0/3WnDTjV1TyUQFuf56+M7Q2wjA0mTu5hZTLMG1BqTen1cifIWsIHd2PO3aIHe9jMCZeq5IFlmX0AGNU1NKnoktrJgMJxf7qW5FxCG+J6Lsje5NGwwwhwzq354AlraX0ipVO/ubwtY+6n6EJjHDlEXDPHrXpuf2TwTfYePhf/eQH4jwJhtvyPW9zwTTXAKlvI+zmvRqKZzIh6ztSmRrjBrt14FzjtddfwFHPwBF6Rc/yUbdzGjefp48kz6U5D8LApf83Xb/j3J9meQMrlPhdzq0FWgwn83tgEsOoMhOworl+Rzz3KwYg2oWaDOyQm3p9vfFSn7bLIU6NdaK0tqvLobBQrTPnXfykweFASt1p5YODSTKwD7eRI+kRJA/LYaCmQTs2pFsBHeQeypSbcKJWCYD6IGHc33mZa8VkInagv1Q/931hN5Y/SPfwC6qzDZwfQWquWRTOqKZnB6oJOWAIXx1/oOLpCTEVAoGeJvWvWexbAyjCddJtfxYbeL2mNwH5cph8NFAfWoFhXMcCdfePpFPeWLXO7BSWsrWUqVXeQUsl88H4h0Fef6Nedmm3ogSuJ3cavw0SPVAoWh/sqS2m7II2fDQm6c4gOE="

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

jdk:
  - oraclejdk11