language: java
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install org.jacoco:jacoco-maven-plugin:report org.sonarsource.scanner.maven:sonar-maven-plugin:3.9.0.2155:sonar -Dsonar.projectKey=codesseur_data-structure

after_success:
  - mvn coveralls:report

addons:
  sonarcloud:
    organization: "codesseur"
    token:
      secure: "fRbNUV/TK+ScF7wgjlXZNB3DxHpd3FgIN7bTbRZbb1Bdv8ivl5jZfr2o4bpBJwlxQuTZ2IaPqRBpnl8VaUnXL3j8yp+QB1/FnQ/5SrbYKRHXAe+imd/8Kovm+/KqdCx3QAnmL3Szs+SWf7YaYCLnKcarOs6vO9+DEEZ6E/vELqwiV9Bne6LD/5e7Q3Q1X3xrYxWq7hSjGTFqbUlo7Aowg2qFXt8S3Tb1zlWSKIsZE1FvuJgDesTA9fs9Yu0L+DGXV560CHfbcH+5N+N9Ofjt+Ckq68xBDFijGJd2DIplmGxtDBaXYaqgDkrw2hORfceBhoGBGdK3UFEX/vbU7fsjKeRGnfU7qF+CmoOtRATdWbPo+Rfvbcg8xsKlUzI6OQA4mzdKdpESlUuxUUGyuxN6oOeTBfS/jiWPNgkrH4c+1Srb8c63hMewiCZvQqiHAdnNQma7jxVD/dxITdnCLvp8aFEyyggqHHhw6x7ai5XfHigtUXtKuKyIW1+doqm0vjsDqxv6Y3+7Ag4IwG/oO5UlK/MIz0HPi7vfuYfQpGZ69iZuvIIFennH3AP2x1H4VRgWHNW7cH65mdD7WpoRFrq4pen8fplFQg0N8Y3PgV7DMPACpWU4JyJEcWydbU9ogw3MtKmlfiy7zlmuHbkZSRbLE7Nrnm7IIWr3Q+zNnh1x6zQ="

cache:
  directories:
    - '$HOME/.m2/repository'

jdk:
  - oraclejdk11