language: java
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install org.jacoco:jacoco-maven-plugin:report sonar:sonar -Dsonar.projectKey=codesseur_better-stream

after_success:
  - mvn coveralls:report

addons:
  sonarcloud:
    organization: "codesseur"
    token:
      secure: "UdPnmYxPWRMATom6MlMXkF7JGwrv4mN06YFrBBAu3fHJoF+NOWQ/o2Kp0wE/PIffAqnXjFBgJ+jUDOwPeMqmvkhGjeuoNsMikPDFc2L7B4GltgeOlu+/XdEPgj8ykDOkksElWpmx8J6fkK6xAosftE1XYlTAJ1sgGwnz8lVXtqobmz2g6g41sCth6nq9+6jnc4p9MOv+mUtNZ5jaFy9NA/qOrqKBjGAVZyJ1D49DFrDduAqerrerA2pfcKSnFiIzVL8QThIyhPxZP0PNknNaBH0Po78lywJMVdHAy+xHLCgbxghf06TacdOCuk2G9Sq3iFvRPnbk3nP5jTlEvAXpWWrjMMBm/AmYs4tNPEZgff9xe1gO2G3oRiZ9i+VHDfTTcLPtXmF7D0SoYb3DVsyyxB1IwEB8jOVpXgUE9/nQQDGXn/ldg/VEof8/+y1vKgXY3YY/FnHv880AFwZWYQtIAhtlQeefiuIW2LfOU+VnhhtsxH+EqhRWFEVWp/BT0fblXGmUJfb0jQqKTgzzNLzBbas81ALG3Oek+/pVH6Vg4h71jnfmx8kgeN92C38amb6c9hFQk1n7shEAiRd+39gWjY2lY+qJUpjmGjFFuLI8jbvhCdYr8FYPI7C58JdL1k4ml/e1cVvZB419Pnyllzc8I5rMjyRlT6R4sgGWEgYdDSY="

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

jdk:
  - oraclejdk11