language: java
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install org.jacoco:jacoco-maven-plugin:report org.sonarsource.scanner.maven:sonar-maven-plugin:3.9.0.2155:sonar -Dsonar.projectKey=codesseur_data-structure

after_success:
  - mvn coveralls:report

addons:
  sonarcloud:
    organization: "codesseur"
    token:
      secure: "cDYmT0A2aIAg28PGmLRNfPA5YmJ4D6TtjWrk8rIcQ2DYoz4XI9YLZaXPnOPkTP27ILbS6UUqRiM8bE8faUQjERZ5W/b9Lmq1VbPQ83qOhj+T55O/sTY7lcusfZx/9ulwGHKmPt/vE6rS1CVaejvQHhh8uVB5YcOGHRZAJ36hTwU/JEjl69U0OhDhdeurXkzY85PwwRovo63XABNtUSrJ5J/zuE5AGMf5/I/lVNaimtMTA7zOQt8EvWsbYyhagrlLIrbRoi4a52A0WGSvy+PnRNadwMy73AgVNPkEovFkT5cvri/pp3KGYYdF6Z5y5/El78bmFnqOKh3VOBG4JTQTcLFuj0jNLg17g9emzVxeOGH/Wbhe2PIzu03HIyhNIynNveG4nwMy3h7Cde2wfEXd7bV4qCqH5/xKvfZ9QhAzR4zAJqVNiL3YtcM/27aZaABsed0YBNoPTOrjCnADVb71O8WQ4K8lRn45UJki0zKjJMz2hf7QwXciuxdt4EorvMYoPOV15K44NhgMON9B3WHxK10lSkEiUG+y3rR2LF/rebCWOu1KG52dk8UIElrQsXMAsFSVxNia0tWHlpNOTHiqp8NS1VKMoa+80T/w4lEDQXP/HWoCiO8LWhKgQ6r+eNYbySimU+QUtA7lDqCc1Qag4WP7MdCaZ7BO6Aa3/92DuTU="

cache:
  directories:
    - '$HOME/.m2/repository'

jdk:
  - oraclejdk11